#!/bin/sh

if [[ $(whoami) != root  ]]; then
	echo "You are not root. You must run this script as root."
	exit
fi

reflector -c 'Serbia' -c 'Hungary' -c 'Romania' --verbose --protocol https --sort rate -f 10 --save /etc/pacman.d/mirrorlist && pacman -Syy
